#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

// js-yaml 로드 (npm install 후 사용 가능)
let yaml;
try {
  yaml = require('js-yaml');
} catch {
  console.error('[graphify] js-yaml 없음. "npm install" 먼저 실행하세요.');
  process.exit(1);
}

// ─── 경로 상수 ────────────────────────────────────────────────────────────────

const VAULT_ROOT = path.resolve(__dirname, '../..');
const GRAPH_DIR  = path.join(VAULT_ROOT, 'graph');

// graphify가 직접 생성하는 경로 (소스 스캔에서 제외)
const AUTO_GENERATED_PREFIXES = ['graph/', 'wiki/communities/', 'wiki/entities/'];

const WIKILINK_RE = /\[\[([^\]|#\n]+?)(?:\|[^\]\n]+)?\]\]/g;

// ─── 파일 스캔 ────────────────────────────────────────────────────────────────

function isAutoGenerated(relPath) {
  const normalized = relPath.replace(/\\/g, '/');
  return AUTO_GENERATED_PREFIXES.some(p => normalized.startsWith(p));
}

function collectMarkdownFiles(dir, vault, acc = []) {
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return acc;
  }
  for (const entry of entries) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
    const full = path.join(dir, entry.name);
    const rel  = path.relative(vault, full).replace(/\\/g, '/');
    if (entry.isDirectory()) {
      collectMarkdownFiles(full, vault, acc);
    } else if (entry.name.endsWith('.md')) {
      acc.push({ full, rel });
    }
  }
  return acc;
}

function parseMarkdownFile({ full, rel }) {
  const raw = fs.readFileSync(full, 'utf8');

  let frontmatter = {};
  let body        = raw;

  if (raw.startsWith('---\n') || raw.startsWith('---\r\n')) {
    const end = raw.indexOf('\n---', 4);
    if (end !== -1) {
      try {
        frontmatter = yaml.load(raw.slice(4, end)) || {};
      } catch {
        frontmatter = {};
      }
      body = raw.slice(end + 4).trimStart();
    }
  }

  // wikilink 추출 (전체 raw에서)
  const links = new Set();
  WIKILINK_RE.lastIndex = 0;
  let m;
  while ((m = WIKILINK_RE.exec(raw)) !== null) {
    links.add(m[1].trim());
  }

  return { rel, frontmatter, body, links: [...links] };
}

// ─── 그래프 빌드 ──────────────────────────────────────────────────────────────

function resolveLink(link, nodes, _fromKey) {
  const noExt = link.replace(/\.md$/, '');
  if (nodes.has(noExt)) return noExt;

  // 파일명(마지막 세그먼트)으로 매칭
  const target = noExt.split('/').pop();
  for (const key of nodes.keys()) {
    if (key.split('/').pop() === target) return key;
  }
  return null;
}

function buildGraph(vault) {
  const files    = collectMarkdownFiles(vault, vault);
  const nodes    = new Map(); // key(relPath without .md) → parsed

  for (const f of files) {
    const parsed = parseMarkdownFile(f);
    const key    = f.rel.replace(/\.md$/, '');
    nodes.set(key, parsed);
  }

  const edges    = [];
  const frontier = new Set();

  for (const [src, node] of nodes) {
    if (isAutoGenerated(src + '.md')) continue;
    for (const link of node.links) {
      const resolved = resolveLink(link, nodes, src);
      if (resolved) {
        edges.push({ from: src, to: resolved });
      } else {
        frontier.add(link);
      }
    }
  }

  return { nodes, edges, frontier };
}

// ─── Audit 리포트 생성 ────────────────────────────────────────────────────────

function generateAudit(graph) {
  const { nodes, edges, frontier } = graph;

  const inDeg  = new Map([...nodes.keys()].map(k => [k, 0]));
  const outDeg = new Map([...nodes.keys()].map(k => [k, 0]));
  for (const { from, to } of edges) {
    outDeg.set(from, (outDeg.get(from) || 0) + 1);
    inDeg.set(to,   (inDeg.get(to)    || 0) + 1);
  }

  const orphans = [];
  for (const [key] of nodes) {
    if (isAutoGenerated(key + '.md')) continue;
    if ((inDeg.get(key) || 0) === 0 && (outDeg.get(key) || 0) === 0) {
      orphans.push(key);
    }
  }

  const stale = [];
  const now   = Date.now();
  for (const [key, node] of nodes) {
    if (isAutoGenerated(key + '.md')) continue;
    const lr = node.frontmatter.last_reviewed;
    if (lr) {
      const d = new Date(lr);
      if (!isNaN(d) && (now - d.getTime()) / 86_400_000 > 180) stale.push(key);
    }
  }

  const today = new Date().toISOString().split('T')[0];
  const frontierList = [...frontier]
    .filter(f => !f.startsWith('http'))
    .slice(0, 50);

  return `---
type: audit
status: mature
confidence: high
owner: knowledge-manager
tags: [graphify, audit, auto-generated]
created: ${today}
last_reviewed: ${today}
---

# Graph Audit Report

Generated: ${today}

## Summary

| 항목 | 개수 |
|------|------|
| 전체 노드 | ${nodes.size} |
| 전체 엣지 | ${edges.length} |
| Orphan | ${orphans.length} |
| Frontier (미생성 링크) | ${frontierList.length} |
| Stale (6개월 초과) | ${stale.length} |

## Orphan 노드

다른 노드와 연결 없는 고립 노드. raw에 보강 노트 추가 권장.

${orphans.length === 0 ? '_없음_' : orphans.map(o => `- \`${o}\``).join('\n')}

## Frontier (위키 갭)

참조되지만 파일이 없는 링크 — LLM이 채울 수 있는 지점.

${frontierList.length === 0 ? '_없음_' : frontierList.map(f => `- \`${f}\``).join('\n')}

## Stale 노드

\`last_reviewed\`가 6개월(180일) 초과인 페이지.

${stale.length === 0 ? '_없음_' : stale.map(s => `- \`${s}\``).join('\n')}

## Contradiction

자동 감지 미지원 — Knowledge Manager가 수동 검토 필요.
`;
}

// ─── Graph JSON 생성 ──────────────────────────────────────────────────────────

function generateGraphJson(graph) {
  const { nodes, edges } = graph;
  const nodeList = [...nodes.entries()].map(([id, n]) => ({
    id,
    type:          n.frontmatter.type          || 'unknown',
    status:        n.frontmatter.status        || 'unknown',
    owner:         n.frontmatter.owner         || null,
    tags:          n.frontmatter.tags          || [],
    last_reviewed: n.frontmatter.last_reviewed || null,
  }));
  return JSON.stringify({ generated: new Date().toISOString(), nodes: nodeList, edges }, null, 2);
}

// ─── Graph HTML 시각화 ────────────────────────────────────────────────────────

function generateGraphHtml(graph) {
  const { nodes, edges } = graph;

  // 노드 타입별 색상
  const COLOR = {
    concept: '#6C8EBF', entity: '#82B366', skill: '#D79B00',
    query: '#9673A6', 'folder-readme': '#808080', audit: '#FF8C00',
    unknown: '#CCCCCC',
  };

  const visNodes = [...nodes.entries()].map(([id, n]) => ({
    id,
    label:  id.split('/').pop(),
    title:  id,
    color:  COLOR[n.frontmatter.type] || COLOR.unknown,
    group:  n.frontmatter.type || 'unknown',
  }));

  const visEdges = edges.map((e, i) => ({ id: i, from: e.from, to: e.to }));

  return `<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<title>2INPER Vault Graph</title>
<script src="https://unpkg.com/vis-network@9.1.9/dist/vis-network.min.js"></script>
<style>
  body { margin: 0; background: #1e1e2e; color: #cdd6f4; font-family: sans-serif; }
  #graph { width: 100vw; height: 100vh; }
  #legend { position: fixed; top: 12px; left: 12px; background: rgba(30,30,46,.85);
            border-radius: 8px; padding: 10px 14px; font-size: 13px; }
  #legend span { display: inline-block; width: 12px; height: 12px; border-radius: 50%;
                 margin-right: 6px; vertical-align: middle; }
  #info { position: fixed; bottom: 12px; left: 12px; background: rgba(30,30,46,.85);
          border-radius: 8px; padding: 8px 12px; font-size: 12px; }
</style>
</head>
<body>
<div id="graph"></div>
<div id="legend">
  <b>2INPER Vault Graph</b><br><br>
  ${Object.entries(COLOR).map(([k, c]) =>
    `<span style="background:${c}"></span>${k}`).join('<br>\n  ')}
</div>
<div id="info">노드 ${visNodes.length}개 &bull; 엣지 ${visEdges.length}개 &bull; ${new Date().toLocaleDateString('ko-KR')}</div>
<script>
const nodes = new vis.DataSet(${JSON.stringify(visNodes)});
const edges = new vis.DataSet(${JSON.stringify(visEdges)});
const container = document.getElementById('graph');
const network = new vis.Network(container, { nodes, edges }, {
  nodes: { shape: 'dot', size: 10, font: { color: '#cdd6f4', size: 11 } },
  edges: { arrows: 'to', color: { color: '#555577', opacity: 0.6 }, width: 1 },
  physics: { stabilization: { iterations: 200 }, barnesHut: { gravitationalConstant: -3000 } },
  interaction: { hover: true, tooltipDelay: 200 }
});
</script>
</body>
</html>`;
}

// ─── LLM Wiki 컴파일러 ────────────────────────────────────────────────────────

async function compileWiki(graph) {
  let Anthropic;
  try {
    Anthropic = require('@anthropic-ai/sdk');
  } catch {
    console.error('[graphify] @anthropic-ai/sdk 없음. "npm install" 먼저 실행하세요.');
    process.exit(1);
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    console.error('[graphify] ANTHROPIC_API_KEY 환경변수가 없습니다.\n  export ANTHROPIC_API_KEY=sk-ant-... 후 재실행하세요.');
    process.exit(1);
  }

  const client = new Anthropic.default();

  const { nodes, frontier } = graph;
  const today = new Date().toISOString().split('T')[0];

  // 1. Frontier 중 wiki/concepts/ 대상
  const newConcepts = [...frontier].filter(f => {
    const n = f.replace(/\\/g, '/');
    return n.startsWith('wiki/concepts/') || n.includes('/concepts/');
  });

  // 2. 거부 피드백이 있는 기존 concept
  const rejectedConcepts = [...nodes.entries()].filter(([key, node]) =>
    key.startsWith('wiki/concepts/') && node.frontmatter.rejection_reason
  );

  if (newConcepts.length === 0 && rejectedConcepts.length === 0) {
    console.log('[graphify] LLM wiki: 생성/갱신 대상 없음');
    return;
  }

  // raw 파일 컨텍스트 수집 (최대 20개, 각 500자)
  const rawSnippets = [...nodes.entries()]
    .filter(([k]) => k.startsWith('raw/'))
    .slice(0, 20)
    .map(([k, n]) => `### ${k}\n${n.body.slice(0, 400)}`)
    .join('\n\n');

  // 시스템 프롬프트
  const systemPrompt = `당신은 2INPER vault의 LLM Wiki 컴파일러입니다.
2INPER는 캐릭터 전문 웹에이전시입니다 — 캐릭터 IP 제작, 상세페이지 제작, 마케팅 대행이 주요 업무입니다.
vault의 raw 노트를 바탕으로 wiki/concepts/ 아래의 개념 페이지를 작성 또는 갱신합니다.

규칙:
- frontmatter 필수 필드: type(concept), status(seed→substantial→mature), owner(knowledge-manager), tags(배열), created, last_reviewed, related(wikilink 배열)
- 본문은 사실 기반. 근거 없는 내용은 추측하지 말고 status: seed로 유지
- 다른 vault 페이지 참조 시 [[wikilink]] 형식
- rejection_reason이 있으면 그 사유를 반영하고 frontmatter에서 rejection_reason 필드 제거
- markdown 파일 전체(frontmatter 포함)를 출력`;

  // 신규 concept 생성
  for (const conceptLink of newConcepts.slice(0, 5)) { // 한 번에 최대 5개
    const name    = conceptLink.split('/').pop();
    const outDir  = path.join(VAULT_ROOT, 'wiki', 'concepts');
    const outPath = path.join(outDir, `${name}.md`);

    if (fs.existsSync(outPath)) continue;

    console.log(`[graphify] LLM → wiki/concepts/${name}.md 생성 중...`);

    const userMsg = `아래 raw 컨텍스트를 바탕으로 "[[wiki/concepts/${name}]]" 개념 페이지를 작성하세요.
today: ${today}

## Raw 컨텍스트 (발췌)
${rawSnippets || '(raw 파일 없음)'}

## 작성할 개념: ${name}`;

    try {
      const resp = await client.messages.create({
        model:      'claude-sonnet-4-6',
        max_tokens: 1024,
        system:     systemPrompt,
        messages:   [{ role: 'user', content: userMsg }],
      });
      const text = resp.content[0].text;
      fs.mkdirSync(outDir, { recursive: true });
      fs.writeFileSync(outPath, text);
      console.log(`[graphify] ✓ wiki/concepts/${name}.md`);
    } catch (err) {
      console.error(`[graphify] ✗ ${name}:`, err.message);
    }
  }

  // 거부 피드백 처리
  for (const [key, node] of rejectedConcepts) {
    const filePath = path.join(VAULT_ROOT, key + '.md');
    const existing = fs.readFileSync(filePath, 'utf8');

    console.log(`[graphify] LLM → ${key} 거부 피드백 반영 중...`);

    const userMsg = `아래 개념 페이지가 거부되었습니다. 거부 사유를 반영해 재작성하세요.
today: ${today}

## 거부 사유
${node.frontmatter.rejection_reason}

## 기존 페이지
${existing}`;

    try {
      const resp = await client.messages.create({
        model:      'claude-sonnet-4-6',
        max_tokens: 1024,
        system:     systemPrompt,
        messages:   [{ role: 'user', content: userMsg }],
      });
      fs.writeFileSync(filePath, resp.content[0].text);
      console.log(`[graphify] ✓ ${key} 갱신`);
    } catch (err) {
      console.error(`[graphify] ✗ ${key}:`, err.message);
    }
  }
}

// ─── Git 훅 설치 ──────────────────────────────────────────────────────────────

function installHooks() {
  const { execSync } = require('child_process');
  const hooksDir = path.join(VAULT_ROOT, 'scripts', 'git-hooks');

  if (!fs.existsSync(hooksDir)) {
    console.error('[graphify] scripts/git-hooks/ 없음');
    process.exit(1);
  }

  // git config
  try {
    execSync('git config core.hooksPath scripts/git-hooks', { cwd: VAULT_ROOT, stdio: 'pipe' });
    console.log('[graphify] git config core.hooksPath = scripts/git-hooks');
  } catch (err) {
    console.error('[graphify] git config 실패:', err.message);
  }

  // chmod +x
  for (const f of fs.readdirSync(hooksDir)) {
    if (f.endsWith('.md')) continue;
    try {
      fs.chmodSync(path.join(hooksDir, f), 0o755);
      console.log(`[graphify] chmod +x scripts/git-hooks/${f}`);
    } catch { /* WSL에서 일부 chmod 실패는 무시 */ }
  }

  // post-commit-graphify 훅 생성 (없으면)
  const pgcPath = path.join(hooksDir, 'post-commit-graphify');
  if (!fs.existsSync(pgcPath)) {
    fs.writeFileSync(pgcPath, `#!/usr/bin/env bash
# graphify 증분 빌드 훅 (백그라운드)
set -euo pipefail
VAULT_ROOT="$(git rev-parse --show-toplevel)"
GRAPHIFY_BIN="$VAULT_ROOT/scripts/graphify/index.js"
if [ -f "$GRAPHIFY_BIN" ]; then
  node "$GRAPHIFY_BIN" update &
fi
exit 0
`);
    try { fs.chmodSync(pgcPath, 0o755); } catch { /* WSL */ }
    console.log('[graphify] scripts/git-hooks/post-commit-graphify 생성');
  }

  console.log('[graphify] 훅 설치 완료');
}

// ─── Watch 모드 ───────────────────────────────────────────────────────────────

function watchMode() {
  console.log(`[graphify] Watch 모드 시작 (vault: ${VAULT_ROOT})`);
  console.log('[graphify] Ctrl+C로 종료');

  let timer = null;

  function rebuild() {
    console.log('[graphify] 변경 감지 — 재빌드...');
    try {
      const graph = buildGraph(VAULT_ROOT);
      fs.mkdirSync(GRAPH_DIR, { recursive: true });
      fs.writeFileSync(path.join(GRAPH_DIR, 'audit.md'),   generateAudit(graph));
      fs.writeFileSync(path.join(GRAPH_DIR, 'graph.json'), generateGraphJson(graph));
      fs.writeFileSync(path.join(GRAPH_DIR, 'graph.html'), generateGraphHtml(graph));
      console.log(`[graphify] 완료 — 노드 ${graph.nodes.size}, 엣지 ${graph.edges.length}`);
    } catch (err) {
      console.error('[graphify] 빌드 오류:', err.message);
    }
  }

  try {
    fs.watch(VAULT_ROOT, { recursive: true }, (_event, filename) => {
      if (!filename || !filename.endsWith('.md')) return;
      const rel = filename.replace(/\\/g, '/');
      if (AUTO_GENERATED_PREFIXES.some(p => rel.startsWith(p))) return;
      clearTimeout(timer);
      timer = setTimeout(rebuild, 600);
    });
  } catch {
    // WSL에서 recursive watch 미지원 시 폴백
    console.warn('[graphify] recursive watch 미지원 — 10초 폴링으로 대체');
    setInterval(rebuild, 10_000);
  }

  rebuild();
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const args  = process.argv.slice(2);
  const flags = new Set(args);

  if (flags.has('--help') || flags.has('-h') || args.length === 0) {
    console.log(`
graphify — 2INPER vault 그래프 빌드 도구 v0.1.0

사용법:
  graphify build               스캔 + graph.json + audit.md + graph.html
  graphify build --wiki        위 + LLM wiki 컴파일 (Claude API 비용 발생)
  graphify build --code-only   코드 AST만 (LLM 0, 미구현 시 full과 동일)
  graphify update              증분 빌드 (현재는 full과 동일)
  graphify --watch             백그라운드 watch 모드
  graphify hook install        git 훅 설치
  graphify --help              이 도움말

환경변수:
  ANTHROPIC_API_KEY  --wiki 모드에 필요
`.trim());
    return;
  }

  const cmd    = args[0];
  const subCmd = args[1];

  fs.mkdirSync(GRAPH_DIR, { recursive: true });

  // --watch
  if (flags.has('--watch')) {
    watchMode();
    return;
  }

  // hook install
  if (cmd === 'hook' && subCmd === 'install') {
    installHooks();
    return;
  }

  // build / update
  if (cmd === 'build' || cmd === 'update') {
    const withWiki  = flags.has('--wiki');

    console.log('[graphify] 스캔 중...');
    const graph = buildGraph(VAULT_ROOT);
    console.log(`[graphify] 노드 ${graph.nodes.size}개, 엣지 ${graph.edges.length}개, frontier ${graph.frontier.size}개`);

    fs.writeFileSync(path.join(GRAPH_DIR, 'audit.md'),   generateAudit(graph));
    console.log('[graphify] graph/audit.md ✓');

    fs.writeFileSync(path.join(GRAPH_DIR, 'graph.json'), generateGraphJson(graph));
    console.log('[graphify] graph/graph.json ✓');

    fs.writeFileSync(path.join(GRAPH_DIR, 'graph.html'), generateGraphHtml(graph));
    console.log('[graphify] graph/graph.html ✓');

    if (withWiki) {
      await compileWiki(graph);
    }

    console.log('[graphify] 완료.');
    return;
  }

  console.error(`[graphify] 알 수 없는 명령: ${cmd}\ngraphify --help 로 도움말 확인`);
  process.exit(1);
}

main().catch(err => {
  console.error('[graphify] 치명적 오류:', err);
  process.exit(1);
});
